Change devon_rex_base to use rbenv to install Ruby

diff --git a/base/Dockerfile b/base/Dockerfile
--- a/base/Dockerfile
+++ b/base/Dockerfile
@@ -1,98 +1,101 @@
-FROM ubuntu:xenial-20190222
+# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+# NOTE: DO *NOT* EDIT THIS FILE.  IT IS GENERATED.
+# PLEASE UPDATE Dockerfile.erb INSTEAD OF THIS FILE
+# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+FROM debian:buster-20190708
 
-ENV DEBIAN_FRONTEND=noninteractive
-RUN apt-get update -y && \
-    apt-get dist-upgrade -y && \
-    apt-get install -y \
-    autoconf \
-    build-essential \
-    imagemagick \
-    libbz2-dev \
-    libcurl4-openssl-dev \
-    libevent-dev \
-    libffi-dev \
-    libglib2.0-dev \
-    libjpeg-dev \
-    libmagickcore-dev \
-    libmagickwand-dev \
-    libmysqlclient-dev \
-    libncurses-dev \
-    libpq-dev \
-    libreadline-dev \
-    libsqlite3-dev \
-    libssl-dev \
-    libxml2-dev \
-    libxslt-dev \
-    libyaml-dev \
-    wget \
-    zlib1g-dev \
-    python-software-properties \
-    software-properties-common \
-    patchutils \
-    curl \
-    procps \
-    language-pack-en \
-    git \
-    unzip \
-    sudo \
-  && rm -rf /var/lib/apt/lists/*
-
-# Add locales
-RUN locale-gen en_US.UTF-8
-
-# Set default locale
-ENV LC_ALL=en_US.UTF-8 \
-    LANG=en_US.UTF-8
-
-RUN update-locale en_US.UTF-8
-
-# Install Ruby to use ruby script in node. e.g.) to expand glob
-# The checksum is defined in https://cache.ruby-lang.org/pub/ruby/index.txt
-ENV RUBY_MAJOR=2.5 \
-    RUBY_VERSION=2.5.1 \
-    RUBY_DOWNLOAD_SHA256=0f5d20f012baca865381a055e73f22db814615fee3c68083182cb78a4b3b30cb
-
-# some of ruby's build scripts are written in ruby
-# we purge this later to make sure our final image uses what we just built
-RUN apt-get update -y \
-  && apt-get install -y bison ruby \
-  && rm -rf /var/lib/apt/lists/* \
-  && mkdir -p /usr/src/ruby \
-  && curl -SL -o /tmp/ruby.tar.bz2 "https://cache.ruby-lang.org/pub/ruby/$RUBY_MAJOR/ruby-$RUBY_VERSION.tar.bz2" \
-  && echo "$RUBY_DOWNLOAD_SHA256 */tmp/ruby.tar.bz2" | sha256sum --check --strict \
-  && tar -xjf /tmp/ruby.tar.bz2 -C /usr/src/ruby --strip-components=1 \
-  && rm -f /tmp/ruby.tar.bz2 \
-  && cd /usr/src/ruby \
-  && autoconf \
-  && ./configure --disable-install-doc \
-  && make -j"$(nproc)" \
-  && apt-get purge -y --auto-remove bison ruby \
-  && make install \
-  && rm -r /usr/src/ruby
-
-ADD gemrc /usr/local/etc/
-ENV GEM_HOME /usr/local/bundle
-ENV PATH $GEM_HOME/bin:$PATH
-
-# Bundler 2 requires rubygems 3.x
-# `gem update --system` will be removed after upgrade Ruby version to 2.6 since
-# the Ruby version uses rubygems v3 to default.
-# See: https://github.com/ruby/ruby/commit/92e726628e3baf4acb1a349089aa4d3278c2ad40
-RUN gem update --system
-
-# Create a user and set relevant environment variables
+ENV GLOBAL_RUBY_VERSION 2.5.5
+ENV BUNDLER1_VERSION 1.17.3
+ENV BUNDLER2_VERSION 2.0.2
+ENV RBENV_COMMIT_HASH 4e923221ce57a04ab52bddd638473d566347711f
+ENV RBENV_RUBY_BUILD_COMMIT_HASH 0e9094b3cba673efb7554f6bd523779c8a3c0bc5
+ENV LANG en_US.UTF-8
+ENV LANGUAGE $LANG
+ENV LC_ALL $LANG
 ENV RUNNER_USER analyzer_runner
 ENV RUNNER_USER_HOME /home/$RUNNER_USER
-RUN adduser --system --home $RUNNER_USER_HOME $RUNNER_USER \
-    && echo 'Defaults always_set_home' >> /etc/sudoers \
-    && echo 'Defaults env_keep += "GEM_HOME"' >> /etc/sudoers \
-    && sed -i -e '/secure_path/d' /etc/sudoers \
-    && echo "Defaults secure_path=\"$GEM_HOME/bin:/usr/local/bin:/usr/bin:/bin\"" >> /etc/sudoers
+ENV DEBIAN_FRONTEND=noninteractive
+ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 
-# Install bundler v1.17.3 not but bundler v2 since runner applications probably parse Gemfile.lock of v1.
-# And, we will keep bundler v1 until the version is out of use.
-# See: https://bundler.io/blog/2019/01/03/announcing-bundler-2.html
-RUN gem install bundler --version 1.17.3 \
-  && gem install bundler --version 2.0.2
+RUN apt-get update -y && \
+    apt-get install -y --no-install-recommends \
+        autoconf \
+        build-essential \
+        imagemagick \
+        libbz2-dev \
+        libcurl4-openssl-dev \
+        libevent-dev \
+        libffi-dev \
+        libglib2.0-dev \
+        libjpeg-dev \
+        libmagickcore-dev \
+        libmagickwand-dev \
+        libmariadb-dev-compat \
+        libncurses-dev \
+        libpq-dev \
+        libreadline-dev \
+        libsqlite3-dev \
+        libssl-dev \
+        libxml2-dev \
+        libxslt-dev \
+        libyaml-dev \
+        wget \
+        zlib1g-dev \
+        software-properties-common \
+        patchutils \
+        curl \
+        procps \
+        locales \
+        tzdata \
+        git \
+        unzip \
+        sudo \
+        ;
+
+# Configure locale
+RUN sed -i -e "s/# ${LANGUAGE}/${LANGUAGE}/" /etc/locale.gen && \
+    locale-gen $LANGUAGE && \
+    dpkg-reconfigure --frontend noninteractive locales
+
+# Clean up
+RUN apt-get -qyy autoremove && \
+    rm -rf /var/lib/apt/lists/* && \
+    apt-get -qyy clean
+
+# Create a user
+RUN adduser --system --shell /bin/bash --home $RUNNER_USER_HOME $RUNNER_USER
+
+
+# Following instructions should be run by $RUNNER_USER
+USER $RUNNER_USER
+
+RUN test `whoami` = "$RUNNER_USER" && \
+    git clone https://github.com/rbenv/rbenv.git ~/.rbenv && \
+    cd ~/.rbenv && \
+    git checkout $RBENV_COMMIT_HASH && \
+    src/configure && \
+    make -j $(nproc) -C src && \
+    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile && \
+    echo 'eval "$(rbenv init -)"' >> ~/.bash_profile && \
+    ~/.rbenv/bin/rbenv init || : && \
+    . ~/.bash_profile && \
+    RBENV_ROOT=$(rbenv root) && \
+    mkdir -p ${RBENV_ROOT}/plugins && \
+    git clone https://github.com/rbenv/ruby-build.git ${RBENV_ROOT}/plugins/ruby-build && \
+    cd ${RBENV_ROOT}/plugins/ruby-build && \
+    git checkout $RBENV_RUBY_BUILD_COMMIT_HASH && \
+    rbenv install --verbose $GLOBAL_RUBY_VERSION && \
+    rbenv global $GLOBAL_RUBY_VERSION && \
+    echo 'install: --no-document' >> ~/.gemrc && \
+    echo 'update: --no-document' >> ~/.gemrc
+
+ENV PATH $RUNNER_USER_HOME/.rbenv/versions/$GLOBAL_RUBY_VERSION/bin:$PATH
+
+# NOTE: Install bundler v1 as well as v2 because runner applications need them
+#       in order to parse both versions of Gemfile.lock.
+#       See https://bundler.io/blog/2019/01/03/announcing-bundler-2.html
+RUN gem install bundler --version $BUNDLER1_VERSION && \
+    gem install bundler --version $BUNDLER2_VERSION
+
 
 WORKDIR /analyzer
